global:
  namespace: apps

backend:
  replicaCount: 1
  image: "dockerpawan09/employee-backend"
  tag: "v5"
  port: 5000
  canaryWeight: 20 # percentage of traffic to route to new version initially

frontend:
  replicaCount: 1
  image: "dockerpawan09/employee-frontend"
  tag: "v5"
  port: 3000  

httpRoute:
  enabled: true
service:
  port: 3000
