apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    canary: 
      steps:
      - setWeight: {{ .Values.backend.canaryWeight }} # Directs traffic to the new version based on canary weight
      - pause: { duration: 1m }                    # Pause for 1 minute for manual/automated validation
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        # 🔐 Dynamically pulling the RDS Connection Endpoint from External Secrets
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: rds-db-secret
              key: DB_HOST

        # 🔐 Dynamically pulling the MariaDB Username from External Secrets
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-db-secret
              key: DB_USER

        # 🔐 Dynamically pulling the active database password securely
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-db-secret
              key: DB_PASSWORD

        # 📂 Target database schema name inside MariaDB
        - name: DB_NAME
          value: "employeedb"
