apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: LoadBalancer # Exposes the frontend application to the internet
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    app: frontend
